spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/me/**,/api/v1/oauth-logins/**,/api/v1/admin/group-quota-policies/**,/api/v1/auth/**,/api/v1/internal/quotas/**
        - id: content-service
          uri: ${CONTENT_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/posts/**,/api/v1/apps/**,/api/v1/reports/**
        - id: media-service
          uri: ${MEDIA_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/v1/assets/**,/api/v1/admin/assets/**
        - id: ai-service
          uri: ${AI_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/v1/ai-sessions/**,/api/v1/ai-quotas/**,/api/v1/ai-characters/**,/api/v1/ai-character-cards/**
